<?php

namespace App\Console\Concerns;

use App\Models\Ledger;
use App\Models\StockItem;
use App\Services\GstService;

/**
 * Phase 9A — the machinery shared by `prove-gstr1` and `prove-gstr3b`.
 *
 * The most important method here is {@see loadSchema()}: both proofs REFUSE to run
 * unless the real GSTN-derived schema is on disk. A returns exporter proven against a
 * remembered schema proves nothing.
 */
trait ProvesGstReturns
{
    /**
     * Load a schema document from `_docs/gstn-schemas/`, or refuse (returns null and
     * prints why). This is the gate the phase's acceptance criteria demand.
     */
    protected function loadSchema(string $file): ?array
    {
        $path = base_path('_docs/gstn-schemas/'.$file);

        if (! is_file($path)) {
            $this->error('Cannot prove the exporter: '.$path.' is missing.');
            $this->line('');
            $this->line('  Place the current GSTR-1 and GSTR-3B JSON schemas (or a valid sample JSON');
            $this->line('  generated by the GST Offline Tool) at:');
            $this->line('      _docs/gstn-schemas/gstr1-schema.json');
            $this->line('      _docs/gstn-schemas/gstr3b-schema.json');
            $this->line('');
            $this->line('  The GSTN schema is versioned and updates periodically; proving the exporter');
            $this->line('  against a stale or invented schema would produce JSONs the portal rejects.');

            return null;
        }

        $data = json_decode((string) file_get_contents($path), true);
        if (! is_array($data) || ! isset($data['_skeleton'])) {
            $this->error($file.' is not a readable schema document (no `_skeleton`).');

            return null;
        }

        $this->line('Schema: '.$file.' · source: '.($data['_meta']['tool_version'] ?? 'unknown'));

        return $data;
    }

    /**
     * Build a GST item-invoice payload for any of the four tax-bearing types, posted
     * through the SAME VoucherScreen::post() a user's keystrokes go through.
     */
    protected function invoiceFactory(GstService $gst, StockItem $item, ?int $godown): callable
    {
        return function (string $type, Ledger $party, Ledger $rev, float $qty, float $rate, string $date, ?int $ref = null) use ($gst, $item, $godown) {
            $base = round($qty * $rate, 2);
            $comp = $gst->computeInvoiceTax($type, $party->state, [['amount' => $base, 'rate' => (float) $item->gst_rate]]);

            $revSide = match ($type) { 'sales' => 'Cr', 'credit_note' => 'Dr', 'debit_note' => 'Cr', default => 'Dr' };
            $partySide = match ($type) { 'sales' => 'Dr', 'credit_note' => 'Cr', 'debit_note' => 'Dr', default => 'Cr' };

            $lines = [['ledger_id' => $rev->id, 'dr_cr' => $revSide, 'amount' => $base]];
            $totalP = (int) round($base * 100);
            foreach ($comp['lines'] as $tl) {
                $lines[] = ['ledger_id' => $tl['ledger_id'], 'dr_cr' => $tl['dr_cr'], 'amount' => $tl['amount']];
            }
            $totalP += $comp['tax_paise'];
            array_unshift($lines, ['ledger_id' => $party->id, 'dr_cr' => $partySide, 'amount' => $totalP / 100]);

            $payload = [
                'type' => $type, 'date' => $date, 'party_ledger_id' => $party->id, 'lines' => $lines,
                'items' => [['stock_item_id' => $item->id, 'godown_id' => $godown, 'qty' => $qty, 'rate' => $rate]],
            ];
            if ($ref) {
                $payload['reference_voucher_id'] = $ref;
            }

            return $payload;
        };
    }

    /**
     * Every currency figure must be exactly 2 decimal places, every rate 2, every
     * quantity 4 — GSTN's JSON is strict about it.
     *
     * @return array<int,string> the violations (empty when clean)
     */
    protected function roundingViolations(array $json): array
    {
        $money = ['txval', 'val', 'iamt', 'camt', 'samt', 'csamt', 'expt_amt', 'nil_amt', 'ngsup_amt', 'inter', 'intra'];
        $rates = ['rt', 'diff_percent'];
        $qtys = ['qty'];
        $bad = [];

        $walk = function ($node, string $path) use (&$walk, &$bad, $money, $rates, $qtys) {
            foreach ($node as $k => $v) {
                $p = $path === '' ? (string) $k : $path.'.'.$k;
                if (is_array($v)) {
                    $walk($v, $p);

                    continue;
                }
                // Only real numbers are checked; a numeric-looking string (pos "27") is not.
                if (! is_int($v) && ! is_float($v)) {
                    continue;
                }
                $f = (float) $v;
                if (in_array($k, $money, true) && abs($f - round($f, 2)) > 1e-9) {
                    $bad[] = $p.' = '.$v.' (money must be 2dp)';
                }
                if (in_array($k, $rates, true) && abs($f - round($f, 2)) > 1e-9) {
                    $bad[] = $p.' = '.$v.' (rate must be 2dp)';
                }
                if (in_array($k, $qtys, true) && abs($f - round($f, 4)) > 1e-9) {
                    $bad[] = $p.' = '.$v.' (quantity must be 4dp)';
                }
            }
        };
        $walk($json, '');

        return $bad;
    }

    /**
     * Structural conformance: every key of the schema's `_skeleton` must be present in
     * the generated document with the right nested shape (object vs array), EXCEPT the
     * keys the schema itself marks optional in `_fields` (e.g. `iamt` on an intra-state
     * line, `gt`, `cname`, `diff_percent`). Optionality is read from the schema file —
     * never assumed here.
     *
     * @return array<int,string> the gaps (empty when conformant)
     */
    protected function conformanceGaps(array $generated, array $schema): array
    {
        $optional = [];
        foreach ($schema['_fields'] ?? [] as $f) {
            if (empty($f['required']) && isset($f['key'])) {
                $optional[$f['key']] = true;
            }
        }

        $gaps = [];
        $walk = function ($skel, $gen, string $path) use (&$walk, &$gaps, $optional) {
            if (! is_array($skel)) {
                return; // a scalar example value — nothing structural to check
            }

            if (array_is_list($skel)) {
                if (! is_array($gen) || (! array_is_list($gen) && $gen !== [])) {
                    $gaps[] = $path.': expected an array';

                    return;
                }
                // Compare the representative row only when we actually produced rows.
                if ($skel !== [] && $gen !== []) {
                    $walk($skel[0], $gen[0], $path.'[]');
                }

                return;
            }

            if (! is_array($gen) || (array_is_list($gen) && $gen !== [])) {
                $gaps[] = $path.': expected an object';

                return;
            }

            foreach ($skel as $k => $v) {
                $child = $path === '' ? (string) $k : $path.'.'.$k;
                if (! array_key_exists($k, $gen)) {
                    if (! isset($optional[$k])) {
                        $gaps[] = $child.': MISSING (schema marks it required)';
                    }

                    continue;
                }
                $walk($v, $gen[$k], $child);
            }
        };

        $walk($schema['_skeleton'], $generated, '');

        return $gaps;
    }

    // ── assertion helpers ───────────────────────────────────────────────────

    protected function section(string $t): void
    {
        $this->line('');
        $this->line('── '.$t.' '.str_repeat('─', max(0, 62 - strlen($t))));
    }

    protected function expect(string $label, $actual, $expected): void
    {
        $pass = $actual === $expected;
        $this->line(($pass ? '  [PASS] ' : '  [FAIL] ').$label.' = '.$this->fmt($actual).($pass ? '' : ' (expected '.$this->fmt($expected).')'));
        $this->ok = $this->ok && $pass;
    }

    protected function expectClose(string $label, $actual, $expected, float $tol = 0.005): void
    {
        $pass = is_numeric($actual) && abs((float) $actual - (float) $expected) < $tol;
        $this->line(($pass ? '  [PASS] ' : '  [FAIL] ').$label.' = '.$this->fmt($actual).($pass ? '' : ' (expected ~'.$this->fmt($expected).')'));
        $this->ok = $this->ok && $pass;
    }

    protected function fmt($v): string
    {
        if (is_array($v)) {
            return $v === [] ? '[] (none)' : json_encode($v);
        }

        return is_bool($v) ? ($v ? 'true' : 'false') : var_export($v, true);
    }
}
