<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: 'DejaVu Sans', sans-serif; }
        body { color: #16211d; font-size: 12px; margin: 0; }
        .wrap { padding: 36px 40px; }
        .top { border-bottom: 3px solid #0B6E4F; padding-bottom: 14px; margin-bottom: 22px; }
        .brand { font-size: 22px; font-weight: bold; color: #0B6E4F; }
        .brand .dot { color: #7fd8b4; }
        .muted { color: #5c6b63; }
        .row { width: 100%; }
        .row td { vertical-align: top; padding: 0; }
        h2 { font-size: 14px; margin: 0 0 6px; color: #0B6E4F; }
        .box { margin-top: 24px; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 8px; }
        table.items th { background: #0B6E4F; color: #fff; text-align: left; padding: 8px 10px; font-size: 11px; }
        table.items td { padding: 8px 10px; border-bottom: 1px solid #dde5e0; }
        .total td { font-weight: bold; border-top: 2px solid #0B6E4F; border-bottom: 0; font-size: 14px; }
        .r { text-align: right; }
        .foot { margin-top: 34px; color: #5c6b63; font-size: 10px; border-top: 1px solid #dde5e0; padding-top: 10px; }
        .pill { background: #e8f6ef; color: #084f39; padding: 2px 8px; border-radius: 10px; font-size: 10px; }
    </style>
</head>
<body>
<div class="wrap">
    <div class="top">
        <table class="row">
            <tr>
                <td><span class="brand"><span class="dot">●</span> {{ $seller['seller_name'] ?? 'ZeroBook' }}</span></td>
                <td class="r">
                    <div style="font-size:18px;font-weight:bold">INVOICE</div>
                    <div class="muted">{{ $number }}</div>
                </td>
            </tr>
        </table>
    </div>

    <table class="row">
        <tr>
            <td width="55%">
                <h2>From</h2>
                <div><strong>{{ $seller['seller_name'] ?? 'ZeroBook' }}</strong></div>
                <div class="muted">{{ $seller['seller_address'] ?? '' }}</div>
                <div class="muted">{{ $seller['seller_email'] ?? '' }}</div>
            </td>
            <td width="45%">
                <h2>Billed to</h2>
                <div><strong>{{ $tenant?->name ?? $payment->tenant_id }}</strong></div>
                <div class="muted">{{ $payment->tenant_id }}.zerobook.in</div>
                <div class="muted" style="margin-top:8px">
                    Invoice date: {{ $issuedOn->format('d-M-Y') }}<br>
                    Payment received: {{ $payment->received_at?->format('d-M-Y') }}<br>
                    Status: <span class="pill">{{ ucfirst($payment->status) }}</span>
                </div>
            </td>
        </tr>
    </table>

    <div class="box">
        <table class="items">
            <thead>
                <tr><th>Description</th><th>Period</th><th class="r">Amount</th></tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <strong>{{ $plan?->name ?? 'Subscription' }}</strong><br>
                        <span class="muted">ZeroBook subscription · {{ $payment->payment_mode }}{{ $payment->reference_number ? ' · ref '.$payment->reference_number : '' }}</span>
                    </td>
                    <td>
                        {{ $payment->subscription_period_start?->format('d-M-Y') }}<br>
                        → {{ $payment->subscription_period_end?->format('d-M-Y') }}
                    </td>
                    <td class="r">{{ $payment->formattedAmount() }}</td>
                </tr>
                <tr class="total">
                    <td colspan="2" class="r">Total paid ({{ $payment->currency }})</td>
                    <td class="r">{{ $payment->formattedAmount() }}</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="foot">
        This is a receipt for your ZeroBook subscription payment. It is not a GST tax invoice.
        Generated by {{ $seller['seller_name'] ?? 'ZeroBook' }} on {{ $issuedOn->format('d-M-Y H:i') }}.
    </div>
</div>
</body>
</html>
